context:
  name: PicoRuby
  version: "3.4.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/${{ name|lower }}/${{ name|lower }}/archive/refs/tags/${{ version }}.tar.gz
    sha256: 6131e3480f3e51943e587c2ddbe9128198f51411d8619e909f85496d74b1671b

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - git
    - ruby
    - if: unix
      then: make
    - if: win
      then: m2-sed
  host:
    - openssl

tests:
  - script:
      - picoruby --verbose -e "puts 'Hello, PicoRuby!'"

about:
  homepage: https://picoruby.org
  repository: https://github.com/picoruby/picoruby
  documentation: https://picoruby.org
  license: MIT
  license_file: LICENSE
  summary: "PicoRuby is the smallest Ruby implementation for one-chip microcontrollers"
  description: |
    PicoRuby is an alternative mruby implementation which is:

    - Small foot print
      - ROM: 256 KB (depending on build config)
      - RAM: 128 KB or less (depending on app code)
      - (Figures in 32 bit architecture)
    - Portable
      - Depends on only standard C library such as glibc, Newlib or Newlib-nano
    - Reference microcontroller boards
      - Raspberry Pi Pico - Arm Cortex-M0+, 264 KB RAM, 2 MB Flash

extra:
  recipe-maintainers:
    - eunos-1128
